---
- name: Run docker containers
  hosts: azure
  gather_facts: true
  tasks:

  - name: copy docker-compose files
    copy:
      src: ./docker-compose.yml
      dest: /home/azureuser

  - name: Run docker-compose file
    shell: 
      "docker-compose up -d"