apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    app: worker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
      - name: worker-app
        image: akshat1902/worker-app
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: worker-app-service
spec:
  selector:
    app: worker-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80